//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3", ConfigurationName="IdnomicRaService.OTPKIRAConnectorSOAPPortType")]
    public interface OTPKIRAConnectorSOAPPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/version", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType version(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/version", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> versionAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/enroll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType enroll(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/enroll", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> enrollAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/list_profiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType list_profiles(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/list_profiles", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> list_profilesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/profile_properties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType profile_properties(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/profile_properties", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> profile_propertiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/revoke", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType revoke(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/revoke", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> revokeAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/recover", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType recover(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/recover", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> recoverAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/renew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType renew(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/renew", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> renewAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/hold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType hold(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/hold", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> holdAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/resume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType resume(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/resume", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> resumeAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/retrieve_cert_author" +
            "ities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType retrieve_cert_authorities(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/retrieve_cert_author" +
            "ities", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> retrieve_cert_authoritiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/certificate_search_p" +
            "roperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType certificate_search_properties(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/certificate_search_p" +
            "roperties", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> certificate_search_propertiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/search_for_certifica" +
            "tes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType search_for_certificates(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentrust.com/OpenTrust/PKI/Connector/RA/SOAP/2.3/search_for_certifica" +
            "tes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OutputParameter")]
        System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> search_for_certificatesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentrust.com/OpenTrust/XML/Message/1.2")]
    public partial class OTMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Message messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Message Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opentrust.com/OpenTrust/XML/Message/1.2")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Array", typeof(Item[]), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HashTable", typeof(Item[]), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(string), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opentrust.com/OpenTrust/XML/Message/1.2")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object item1Field;
        
        private Item1ChoiceType item1ElementNameField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Array", typeof(Item[]), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HashTable", typeof(Item[]), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(string), IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item1ChoiceType Item1ElementName {
            get {
                return this.item1ElementNameField;
            }
            set {
                this.item1ElementNameField = value;
                this.RaisePropertyChanged("Item1ElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentrust.com/OpenTrust/XML/Message/1.2", IncludeInSchema=false)]
    public enum Item1ChoiceType {
        
        /// <remarks/>
        Array,
        
        /// <remarks/>
        HashTable,
        
        /// <remarks/>
        Value,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentrust.com/OpenTrust/XML/Message/1.2", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Array,
        
        /// <remarks/>
        HashTable,
        
        /// <remarks/>
        Value,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OTPKIRAConnectorSOAPPortTypeChannel : Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTPKIRAConnectorSOAPPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OTPKIRAConnectorSOAPPortTypeClient : System.ServiceModel.ClientBase<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTPKIRAConnectorSOAPPortType>, Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTPKIRAConnectorSOAPPortType {
        
        public OTPKIRAConnectorSOAPPortTypeClient() {
        }
        
        public OTPKIRAConnectorSOAPPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OTPKIRAConnectorSOAPPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTPKIRAConnectorSOAPPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTPKIRAConnectorSOAPPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType version(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.version(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> versionAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.versionAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType enroll(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.enroll(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> enrollAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.enrollAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType list_profiles(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.list_profiles(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> list_profilesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.list_profilesAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType profile_properties(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.profile_properties(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> profile_propertiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.profile_propertiesAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType revoke(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.revoke(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> revokeAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.revokeAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType recover(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.recover(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> recoverAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.recoverAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType renew(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.renew(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> renewAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.renewAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType hold(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.hold(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> holdAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.holdAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType resume(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.resume(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> resumeAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.resumeAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType retrieve_cert_authorities(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.retrieve_cert_authorities(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> retrieve_cert_authoritiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.retrieve_cert_authoritiesAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType certificate_search_properties(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.certificate_search_properties(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> certificate_search_propertiesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.certificate_search_propertiesAsync(InputParameter);
        }
        
        public Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType search_for_certificates(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.search_for_certificates(InputParameter);
        }
        
        public System.Threading.Tasks.Task<Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType> search_for_certificatesAsync(Keyfactor.AnyGateway.IdnomicCaProxy.IdnomicRaService.OTMessageType InputParameter) {
            return base.Channel.search_for_certificatesAsync(InputParameter);
        }
    }
}
